Medhansh Gupta - 25070123074

Exp 9: Tools for EDA - Study of Numpy Library

In [ ]:
# Numpy: faster than lists, used for numerical computation, base for pandas.

In [2]:
# Declaration of Numpy
import numpy as np
a = np.array([1,10,20,30,40,50,500])
b = np.array([[1,2,3],[4,5,6]])
print(a)
print(b)

[  1  10  20  30  40  50 500]
[[1 2 3]
 [4 5 6]]


In [3]:
# Dimension of Array
print(a.ndim)
print(b.ndim)

1
2


In [4]:
# size of array
print(a.size)
print(b.size)

7
6


In [6]:
a.dtype

dtype('int64')

In [8]:
#inbuilt functions using numpy
np.zeros((2,3))


array([[0., 0., 0.],
       [0., 0., 0.]])

In [9]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [11]:
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [12]:
np.eye((3))

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [13]:
np.linspace(0,1,4)

array([0.        , 0.33333333, 0.66666667, 1.        ])

In [14]:
print(b * 2)
print(a + 5)

[[ 2  4  6]
 [ 8 10 12]]
[  6  15  25  35  45  55 505]


In [20]:
np.mean(a)

np.float64(93.0)

In [16]:
np.median(a)

np.float64(30.0)

In [17]:
np.max(a)

np.int64(500)

In [18]:
np.min(a)

np.int64(1)

In [19]:
np.sum(a)

np.int64(651)